apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-reviews
  namespace: student47-bookinfo-dev
  labels:
    app: bookinfo-dev-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-reviews
  template:
    metadata:
      labels:
        app: bookinfo-dev-reviews
    spec:
      containers:
      - name: bookinfo-dev-reviews
        image: ghcr.io/supakit25433/bookinfo-reviews:dev
        imagePullPolicy: Always
        env:
        - name: ENABLE_RATINGS
          value: "true"
        - name: RATINGS_SERVICE
          value: "http://sitkmutt.bookinfo.dev.opsta.net/student47/ratings"
      imagePullSecrets:
        - name: registry-bookinfo